In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
# uci repository : https://archive.ics.uci.edu/ml/index.php

path = 'https://archive.ics.uci.edu/ml/machine-learning-databases/\
breast-cancer-wisconsin/breast-cancer-wisconsin.data'

In [5]:
pd.read_csv(path)

1000025  5   1  1.1  1.2  2 1.3   3  1.4  1.5  2.1
0    1002945  5   4    4    5  7  10   3    2    1    2
1    1015425  3   1    1    1  2   2   3    1    1    2
2    1016277  6   8    8    1  3   4   3    7    1    2
3    1017023  4   1    1    3  2   1   3    1    1    2
4    1017122  8  10   10    8  7  10   9    7    1    4
..       ... ..  ..  ...  ... ..  ..  ..  ...  ...  ...
693   776715  3   1    1    1  3   2   1    1    1    2
694   841769  2   1    1    1  2   1   1    1    1    2
695   888820  5  10   10    3  7   3   8   10    2    4
696   897471  4   8    6    4  3   4  10    6    1    4
697   897471  4   8    8    5  4   5  10    4    1    4

[698 rows x 11 columns]

In [7]:
df = pd.read_csv(path, header=None)

In [8]:
# 열 이름 지정
df.columns = ['id','clump','cell_size','cell_shape', 'adhesion','epithlial',
              'bare_nuclei','chromatin','normal_nucleoli', 'mitoses', 'class'] 

In [9]:
#  IPython 디스플레이 설정 - 출력할 열의 개수 한도 늘리기
pd.set_option('display.max_columns', 15)

In [10]:
df.head(3)

id  clump  cell_size  cell_shape  adhesion  epithlial bare_nuclei  \
0  1000025      5          1           1         1          2           1   
1  1002945      5          4           4         5          7          10   
2  1015425      3          1           1         1          2           2   

   chromatin  normal_nucleoli  mitoses  class  
0          3                1        1      2  
1          3                2        1      2  
2          3                1        1      2

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   id               699 non-null    int64 
 1   clump            699 non-null    int64 
 2   cell_size        699 non-null    int64 
 3   cell_shape       699 non-null    int64 
 4   adhesion         699 non-null    int64 
 5   epithlial        699 non-null    int64 
 6   bare_nuclei      699 non-null    object
 7   chromatin        699 non-null    int64 
 8   normal_nucleoli  699 non-null    int64 
 9   mitoses          699 non-null    int64 
 10  class            699 non-null    int64 
dtypes: int64(10), object(1)
memory usage: 60.2+ KB


In [12]:
df.bare_nuclei 

0       1
1      10
2       2
3       4
4       1
       ..
694     2
695     1
696     3
697     4
698     5
Name: bare_nuclei, Length: 699, dtype: object

In [13]:
df.bare_nuclei.unique()

array(['1', '10', '2', '4', '3', '9', '7', '?', '5', '8', '6'],
      dtype=object)

In [15]:
df.bare_nuclei.replace('?', np.nan, inplace=True)

In [16]:
df.dropna(subset=['bare_nuclei'], axis=0, inplace=True)

In [17]:
df.head(3)

id  clump  cell_size  cell_shape  adhesion  epithlial bare_nuclei  \
0  1000025      5          1           1         1          2           1   
1  1002945      5          4           4         5          7          10   
2  1015425      3          1           1         1          2           2   

   chromatin  normal_nucleoli  mitoses  class  
0          3                1        1      2  
1          3                2        1      2  
2          3                1        1      2

In [18]:
df.bare_nuclei.unique()

array(['1', '10', '2', '4', '3', '9', '7', '5', '8', '6'], dtype=object)

In [19]:
df.bare_nuclei = df.bare_nuclei.astype('int')

In [20]:
df.head(3)

id  clump  cell_size  cell_shape  adhesion  epithlial  bare_nuclei  \
0  1000025      5          1           1         1          2            1   
1  1002945      5          4           4         5          7           10   
2  1015425      3          1           1         1          2            2   

   chromatin  normal_nucleoli  mitoses  class  
0          3                1        1      2  
1          3                2        1      2  
2          3                1        1      2

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 683 entries, 0 to 698
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               683 non-null    int64
 1   clump            683 non-null    int64
 2   cell_size        683 non-null    int64
 3   cell_shape       683 non-null    int64
 4   adhesion         683 non-null    int64
 5   epithlial        683 non-null    int64
 6   bare_nuclei      683 non-null    int32
 7   chromatin        683 non-null    int64
 8   normal_nucleoli  683 non-null    int64
 9   mitoses          683 non-null    int64
 10  class            683 non-null    int64
dtypes: int32(1), int64(10)
memory usage: 61.4 KB


In [22]:
df.describe()

id       clump   cell_size  cell_shape    adhesion  \
count  6.830000e+02  683.000000  683.000000  683.000000  683.000000   
mean   1.076720e+06    4.442167    3.150805    3.215227    2.830161   
std    6.206440e+05    2.820761    3.065145    2.988581    2.864562   
min    6.337500e+04    1.000000    1.000000    1.000000    1.000000   
25%    8.776170e+05    2.000000    1.000000    1.000000    1.000000   
50%    1.171795e+06    4.000000    1.000000    1.000000    1.000000   
75%    1.238705e+06    6.000000    5.000000    5.000000    4.000000   
max    1.345435e+07   10.000000   10.000000   10.000000   10.000000   

        epithlial  bare_nuclei   chromatin  normal_nucleoli     mitoses  \
count  683.000000   683.000000  683.000000       683.000000  683.000000   
mean     3.234261     3.544656    3.445095         2.869693    1.603221   
std      2.223085     3.643857    2.449697         3.052666    1.732674   
min      1.000000     1.000000    1.000000         1.000000    1.000000   
25%      2.000000     1.000000    2.000000         1.000000    1.000000   
50%      2.000000     1.000000    3.000000         1.000000    1.000000   
75%      4.000000     6.000000    5.000000         4.000000    1.000000   
max     10.000000    10.000000   10.000000        10.000000   10.000000   

            class  
count  683.000000  
mean     2.699854  
std      0.954592  
min      2.000000  
25%      2.000000  
50%      2.000000  
75%      4.000000  
max      4.000000

In [23]:
# 데이터 셋 구분 (훈련용, 테스트용)

# 속성(변수) 선택 

x=df[['clump','cell_size','cell_shape', 'adhesion','epithlial',
      'bare_nuclei','chromatin','normal_nucleoli', 'mitoses']]  #설명 변수 X

y=df['class']

In [24]:
# 정규화 
# 단위가 틀리네(독립변수)

from sklearn.preprocessing import StandardScaler

StandardScaler().fit_transform(x)

array([[ 0.19790469, -0.70221201, -0.74177362, ..., -0.18182716,
        -0.61292736, -0.34839971],
       [ 0.19790469,  0.27725185,  0.26278299, ..., -0.18182716,
        -0.28510482, -0.34839971],
       [-0.51164337, -0.70221201, -0.74177362, ..., -0.18182716,
        -0.61292736, -0.34839971],
       ...,
       [ 0.19790469,  2.23617957,  2.2718962 , ...,  1.86073779,
         2.33747554,  0.22916583],
       [-0.15686934,  1.58320366,  0.93248739, ...,  2.67776377,
         1.02618536, -0.34839971],
       [-0.15686934,  1.58320366,  1.6021918 , ...,  2.67776377,
         0.37054027, -0.34839971]])

In [25]:
x = StandardScaler().fit_transform(x)

In [26]:
# data set 구분 (7:3 비율)
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test =\
train_test_split(x,y, 
                test_size=0.3,
                random_state=42)

In [27]:
x_train, x_train.shape

(array([[ 0.19790469,  1.58320366,  1.6021918 , ...,  1.4522248 ,
          1.68183045, -0.34839971],
        [ 0.55267873, -0.70221201, -0.74177362, ..., -0.99885314,
         -0.61292736, -0.34839971],
        [ 0.19790469, -0.70221201, -0.74177362, ..., -0.59034015,
         -0.61292736, -0.34839971],
        ...,
        [ 1.97177486,  0.6037398 ,  1.2673396 , ..., -0.18182716,
          0.04271773,  3.69455903],
        [-0.15686934, -0.70221201, -0.74177362, ..., -0.59034015,
         -0.61292736, -0.34839971],
        [ 1.97177486,  2.23617957,  2.2718962 , ...,  1.86073779,
          1.68183045,  3.69455903]]),
 (478, 9))

In [28]:
x_test, x_test.shape

(array([[ 1.26222679, -0.0492361 ,  0.26278299, ..., -0.18182716,
          0.04271773, -0.34839971],
        [ 1.26222679,  1.58320366,  1.2673396 , ...,  1.4522248 ,
          1.68183045,  3.1169935 ],
        [-1.22119144, -0.70221201, -0.74177362, ..., -0.18182716,
         -0.61292736, -0.34839971],
        ...,
        [ 1.26222679,  2.23617957,  2.2718962 , ..., -0.18182716,
          2.33747554,  4.8496901 ],
        [-0.51164337, -0.70221201, -0.74177362, ..., -0.99885314,
         -0.61292736, -0.34839971],
        [-0.51164337, -0.70221201, -0.74177362, ..., -0.59034015,
         -0.61292736, -0.34839971]]),
 (205, 9))

모델링

In [29]:
from sklearn.tree import *

In [30]:
model = DecisionTreeClassifier(criterion='entropy', max_depth=5)

In [31]:
# 모델 학습 
model.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=5)

In [32]:
# test data로 예측, 분류 

model.predict(x_test)

array([4, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 4, 4, 2, 4, 2, 4, 4, 2,
       4, 2, 2, 2, 4, 4, 2, 4, 2, 4, 4, 4, 2, 2, 4, 2, 4, 4, 2, 4, 4, 2,
       2, 4, 2, 4, 2, 4, 2, 2, 2, 4, 2, 4, 2, 2, 2, 4, 2, 2, 2, 4, 2, 2,
       4, 4, 2, 2, 4, 2, 2, 2, 4, 4, 2, 2, 4, 4, 4, 4, 2, 4, 2, 4, 2, 2,
       4, 2, 2, 4, 2, 4, 2, 2, 2, 4, 2, 2, 2, 2, 4, 2, 2, 4, 2, 2, 4, 2,
       4, 4, 2, 2, 2, 2, 4, 2, 2, 2, 4, 4, 2, 2, 2, 2, 4, 2, 4, 2, 2, 2,
       4, 4, 4, 2, 2, 2, 4, 2, 4, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 4, 2,
       2, 2, 2, 2, 4, 2, 4, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 2, 2, 4, 2, 2,
       4, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 2, 2, 2, 4, 2, 4, 2, 4, 4, 2, 2,
       2, 2, 4, 4, 4, 2, 2], dtype=int64)

In [33]:
y_hat = model.predict(x_test)

In [34]:
# 성능평가 (confusion matrix)

from sklearn.metrics import *

In [35]:
confusion_matrix(y_test, y_hat) # (실제값, 예측값)

array([[125,   2],
       [  5,  73]], dtype=int64)

In [37]:
print(classification_report(y_test, y_hat))

              precision    recall  f1-score   support

           2       0.96      0.98      0.97       127
           4       0.97      0.94      0.95        78

    accuracy                           0.97       205
   macro avg       0.97      0.96      0.96       205
weighted avg       0.97      0.97      0.97       205



In [ ]:
# 결과해석 
# acc(정확도) : 0.97 
# f1 score :  미생존자(0) 0.97, 생존자(1) 0.95