In [16]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import folium

In [2]:
# 서울 시내 중학교 진학률 데이터셋 

file_path = '2016_middle_shcool_graduates_report.xlsx'

In [6]:
df = pd.read_excel(file_path, header=0)
df.head()

Unnamed: 0   지역               학교명  코드  유형  주야  남학생수  여학생수    일반고   특성화고  \
0           0  성북구    서울대학교사범대학부설중학교   3  국립  주간   277     0  0.585  0.148   
1           1  종로구  서울대학교사범대학부설여자중학교   3  국립  주간     0   256  0.680  0.199   
2           2  강남구             개원중학교   3  공립  주간   170   152  0.817  0.047   
3           3  강남구             개포중학교   3  공립  주간    83    72  0.755  0.097   
4           4  서초구             경원중학교   3  공립  주간   199   212  0.669  0.017   

   ...  외고_국제고  예고_체고  마이스터고    자사고    자공고   기타진학  취업     미상         위도  \
0  ...   0.007  0.000  0.011  0.227  0.000  0.004   0  0.000  37.594942   
1  ...   0.035  0.008  0.000  0.043  0.004  0.031   0  0.000  37.577473   
2  ...   0.012  0.003  0.006  0.090  0.003  0.009   0  0.003  37.491637   
3  ...   0.013  0.019  0.019  0.065  0.000  0.019   0  0.000  37.480439   
4  ...   0.010  0.005  0.000  0.282  0.000  0.010   0  0.000  37.510750   

           경도  
0  127.038909  
1  127.003857  
2  127.071744  
3  127.062201  
4  127.008900  

[5 rows x 21 columns]

In [7]:
# IPython Console 디스플레이 옵션 설정하기
pd.set_option('display.width', None)        # 출력화면의 너비
pd.set_option('display.max_rows', 100)      # 출력할 행의 개수 한도
pd.set_option('display.max_columns', 10)    # 출력할 열의 개수 한도
pd.set_option('display.max_colwidth', 20)   # 출력할 열의 너비
pd.set_option('display.unicode.east_asian_width', True)   # 유니코드 사용 너비 조정

In [8]:
df.columns

Index(['Unnamed: 0', '지역', '학교명', '코드', '유형', '주야', '남학생수',
       '여학생수', '일반고', '특성화고', '과학고', '외고_국제고', '예고_체고',
       '마이스터고', '자사고', '자공고', '기타진학', '취업', '미상', '위도',
       '경도'],
      dtype='object')

In [9]:
df.columns.values

array(['Unnamed: 0', '지역', '학교명', '코드', '유형', '주야', '남학생수', '여학생수', '일반고',
       '특성화고', '과학고', '외고_국제고', '예고_체고', '마이스터고', '자사고', '자공고', '기타진학',
       '취업', '미상', '위도', '경도'], dtype=object)

EDA

In [10]:
df.head(3)

Unnamed: 0    지역                               학교명  코드  유형  ...  \
0           0  성북구  서울대학교사범대학부설중학교.....       3  국립  ...   
1           1  종로구  서울대학교사범대학부설여자중학교...     3  국립  ...   
2           2  강남구           개원중학교                     3  공립  ...   

  기타진학  취업   미상       위도        경도  
0    0.004     0  0.000  37.594942  127.038909  
1    0.031     0  0.000  37.577473  127.003857  
2    0.009     0  0.003  37.491637  127.071744  

[3 rows x 21 columns]

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 415 entries, 0 to 414
Data columns (total 21 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  415 non-null    int64  
 1   지역          415 non-null    object 
 2   학교명         415 non-null    object 
 3   코드          415 non-null    int64  
 4   유형          415 non-null    object 
 5   주야          415 non-null    object 
 6   남학생수        415 non-null    int64  
 7   여학생수        415 non-null    int64  
 8   일반고         415 non-null    float64
 9   특성화고        415 non-null    float64
 10  과학고         415 non-null    float64
 11  외고_국제고      415 non-null    float64
 12  예고_체고       415 non-null    float64
 13  마이스터고       415 non-null    float64
 14  자사고         415 non-null    float64
 15  자공고         415 non-null    float64
 16  기타진학        415 non-null    float64
 17  취업          415 non-null    int64  
 18  미상          415 non-null    float64
 19  위도          415 non-null    f

In [12]:
df.describe()

Unnamed: 0        코드    남학생수    여학생수      일반고  ...  \
count  415.000000  415.000000  415.000000  415.000000  415.000000  ...   
mean   207.000000    3.197590  126.532530  116.173494    0.623080  ...   
std    119.944432    0.804272   79.217906   76.833082    0.211093  ...   
min      0.000000    3.000000    0.000000    0.000000    0.000000  ...   
25%    103.500000    3.000000   80.000000   71.500000    0.566500  ...   
50%    207.000000    3.000000  129.000000  118.000000    0.681000  ...   
75%    310.500000    3.000000  177.500000  161.500000    0.758000  ...   
max    414.000000    9.000000  337.000000  422.000000    0.908000  ...   

         기타진학   취업        미상        위도        경도  
count  415.000000  415.0  415.000000  415.000000  415.000000  
mean     0.069571    0.0    0.001670   37.491969  127.032792  
std      0.235630    0.0    0.003697    0.348926    0.265245  
min      0.000000    0.0    0.000000   34.979940  126.639561  
25%      0.000000    0.0    0.000000   37.501934  126.921758  
50%      0.007000    0.0    0.000000   37.547702  127.013579  
75%      0.015000    0.0    0.003000   37.590670  127.071265  
max      1.000000    0.0    0.036000   37.694777  129.106974  

[8 rows x 17 columns]

In [13]:
df.head(1)

Unnamed: 0    지역                             학교명  코드  유형  ...  \
0           0  성북구  서울대학교사범대학부설중학교.....     3  국립  ...   

  기타진학  취업  미상       위도        경도  
0    0.004     0   0.0  37.594942  127.038909  

[1 rows x 21 columns]

In [14]:
df = df.drop(['Unnamed: 0'], axis=1)

In [15]:
df.head(3)

지역                               학교명  코드  유형  주야  ...  \
0  성북구  서울대학교사범대학부설중학교.....       3  국립  주간  ...   
1  종로구  서울대학교사범대학부설여자중학교...     3  국립  주간  ...   
2  강남구           개원중학교                     3  공립  주간  ...   

   기타진학  취업   미상       위도        경도  
0     0.004     0  0.000  37.594942  127.038909  
1     0.031     0  0.000  37.577473  127.003857  
2     0.009     0  0.003  37.491637  127.071744  

[3 rows x 20 columns]

In [17]:
folium.Map(location=[37.594942,127.038909], zoom_start=12)

In [18]:
folium.Map(location=[37.594942,127.038909], 
           tiles='Stamen Terrain',
           zoom_start=12)

In [20]:
folium.Map(location=[37.55,126.98], 
                        tiles='Stamen Terrain',
                        zoom_start=12)

In [21]:
mschool_map = folium.Map(location=[37.55,126.98], 
                        tiles='Stamen Terrain',
                        zoom_start=12)

In [19]:
df.head(3)

지역                               학교명  코드  유형  주야  ...  \
0  성북구  서울대학교사범대학부설중학교.....       3  국립  주간  ...   
1  종로구  서울대학교사범대학부설여자중학교...     3  국립  주간  ...   
2  강남구           개원중학교                     3  공립  주간  ...   

   기타진학  취업   미상       위도        경도  
0     0.004     0  0.000  37.594942  127.038909  
1     0.031     0  0.000  37.577473  127.003857  
2     0.009     0  0.003  37.491637  127.071744  

[3 rows x 20 columns]

In [23]:
# 중학교 위치 정보를 circle marker 로 표시 

for name, lat, lng in zip(df.학교명, df.위도, df.경도):
    folium.CircleMarker([lat, lng],
                       radius=5,    # 원의 반지름
                       color='brown',
                       fill=True,
                       fill_color='coral',
                       fill_opacity= 0.7, # 투명도
                       popup=name).add_to(mschool_map)

In [24]:
mschool_map.save('mschool.html')

데이터 전처리

In [25]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [26]:
le = LabelEncoder() 
oh = OneHotEncoder()

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 415 entries, 0 to 414
Data columns (total 20 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   지역      415 non-null    object 
 1   학교명     415 non-null    object 
 2   코드      415 non-null    int64  
 3   유형      415 non-null    object 
 4   주야      415 non-null    object 
 5   남학생수    415 non-null    int64  
 6   여학생수    415 non-null    int64  
 7   일반고     415 non-null    float64
 8   특성화고    415 non-null    float64
 9   과학고     415 non-null    float64
 10  외고_국제고  415 non-null    float64
 11  예고_체고   415 non-null    float64
 12  마이스터고   415 non-null    float64
 13  자사고     415 non-null    float64
 14  자공고     415 non-null    float64
 15  기타진학    415 non-null    float64
 16  취업      415 non-null    int64  
 17  미상      415 non-null    float64
 18  위도      415 non-null    float64
 19  경도      415 non-null    float64
dtypes: float64(12), int64(4), object(4)
memory usage: 65.0+ KB


In [28]:
df.코드.unique()

array([3, 5, 9], dtype=int64)

In [29]:
le.fit_transform(df.코드)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [32]:
le.fit_transform(df.지역)

array([16, 22,  0,  0, 14,  0,  0,  0,  0,  0,  0,  0,  0, 14, 14, 14,  0,
       14, 14, 14, 14, 14,  0,  0,  0, 14, 14,  0, 14,  0,  0,  0, 14, 14,
        0, 14,  0,  0,  0,  0, 17, 17,  1, 17,  1,  1,  1,  1,  1, 17, 17,
       17, 17,  1, 17, 17,  1, 17,  1,  1, 17, 17,  1,  1, 17, 17, 17, 17,
       17, 17, 17, 17, 17, 17,  1,  1, 17, 17,  1,  1, 18,  3,  3,  3, 18,
        3,  3,  3,  3,  3,  3, 18, 18,  3,  3,  3, 18,  3,  3,  3, 18, 18,
       18, 18, 18,  3, 18, 18, 18, 18, 18, 18,  3, 18, 18,  3,  3,  7,  6,
        6,  6,  6,  6,  7, 19, 19, 19, 19,  7, 19,  7,  7,  7,  7,  6,  7,
       19, 19, 19, 19,  6,  6, 19,  6,  6,  6,  6, 19,  7, 10, 10, 10, 10,
       10, 24, 24, 24, 24, 10, 24, 10, 24, 24, 24, 24, 24, 10, 10, 10, 10,
       10, 24, 24, 10, 24, 24, 10, 10, 11, 11,  4,  4, 11,  4,  4,  4, 11,
        4, 11, 11, 11, 11,  4,  4,  4, 11, 11, 11,  4, 11,  4,  4,  4,  4,
       11,  4, 11, 11,  8,  8,  9,  8,  8,  8,  9,  9,  9,  9,  8,  8,  8,
        8,  8,  8,  9,  8

In [33]:
_loc = le.fit_transform(df.지역)
_code = le.fit_transform(df.코드)
_type = le.fit_transform(df.유형)
_day = le.fit_transform(df.주야)

In [34]:
df.head(3)

지역                               학교명  코드  유형  주야  ...  \
0  성북구  서울대학교사범대학부설중학교.....       3  국립  주간  ...   
1  종로구  서울대학교사범대학부설여자중학교...     3  국립  주간  ...   
2  강남구           개원중학교                     3  공립  주간  ...   

   기타진학  취업   미상       위도        경도  
0     0.004     0  0.000  37.594942  127.038909  
1     0.031     0  0.000  37.577473  127.003857  
2     0.009     0  0.003  37.491637  127.071744  

[3 rows x 20 columns]

In [36]:
df['location'] = _loc 
df['code'] = _code
df['type'] = _type
df['day'] = _day

In [37]:
df.head(3)

지역                               학교명  코드  유형  주야  ...  \
0  성북구  서울대학교사범대학부설중학교.....       3  국립  주간  ...   
1  종로구  서울대학교사범대학부설여자중학교...     3  국립  주간  ...   
2  강남구           개원중학교                     3  공립  주간  ...   

         경도  location  code  type  day  
0  127.038909        16     0     1    0  
1  127.003857        22     0     1    0  
2  127.071744         0     0     0    0  

[3 rows x 24 columns]

모델링 

In [39]:
# DBSCAN 

from sklearn.cluster import *

In [40]:
# 분석에 사용할 속성 선택(과학고, 외고_국제고, 자사고)

columns_list = [9, 10, 13]
df.iloc[:, columns_list]

과학고  외고_국제고  자사고
0     0.018        0.007   0.227
1     0.000        0.035   0.043
2     0.009        0.012   0.090
3     0.013        0.013   0.065
4     0.007        0.010   0.282
..      ...          ...     ...
410   0.000        0.000   0.000
411   0.000        0.000   0.000
412   0.000        0.000   0.000
413   0.000        0.000   0.000
414   0.000        0.024   0.010

[415 rows x 3 columns]

In [41]:
x = df.iloc[:, columns_list]
x[:5]

과학고  외고_국제고  자사고
0   0.018        0.007   0.227
1   0.000        0.035   0.043
2   0.009        0.012   0.090
3   0.013        0.013   0.065
4   0.007        0.010   0.282

In [42]:
x.head()

과학고  외고_국제고  자사고
0   0.018        0.007   0.227
1   0.000        0.035   0.043
2   0.009        0.012   0.090
3   0.013        0.013   0.065
4   0.007        0.010   0.282

In [43]:
# 정규화 

from sklearn.preprocessing import StandardScaler

StandardScaler().fit_transform(x)

array([[ 2.02375287, -0.57972902,  1.84751715],
       [-0.65047921,  1.84782097, -0.48039958],
       [ 0.68663683, -0.14623795,  0.11423133],
       ...,
       [-0.65047921, -1.18661652, -1.0244236 ],
       [-0.65047921, -1.18661652, -1.0244236 ],
       [-0.65047921,  0.89414062, -0.89790638]])

In [44]:
x = StandardScaler().fit_transform(x)

In [45]:
# 모델링 (DBSCAN)

model = DBSCAN(eps=0.2, min_samples=5)

In [46]:
model.fit(x)

DBSCAN(eps=0.2)

In [47]:
# 예측
model.labels_

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  0, -1, -1, -1,
       -1, -1, -1,  2, -1,  0, -1, -1, -1, -1, -1,  0, -1, -1, -1, -1, -1,
        0,  3, -1, -1, -1, -1, -1, -1, -1,  0, -1, -1,  1,  0, -1, -1, -1,
        0, -1, -1, -1, -1,  0, -1,  0,  0, -1, -1,  0, -1, -1, -1,  0,  0,
       -1, -1,  0, -1, -1, -1,  0, -1, -1, -1,  0,  2,  0,  0,  0,  0,  0,
       -1, -1, -1,  0, -1,  0, -1, -1,  0, -1,  0, -1,  0,  0, -1, -1, -1,
       -1,  1,  0, -1,  0,  0, -1, -1, -1,  0, -1, -1, -1, -1, -1,  0,  1,
       -1, -1,  0,  2,  0, -1, -1,  1, -1, -1, -1,  0,  0,  0, -1, -1,  0,
       -1, -1, -1,  0,  0, -1, -1, -1, -1,  0, -1, -1, -1,  0, -1, -1, -1,
        0, -1,  0,  0, -1, -1, -1, -1, -1,  0, -1,  0,  0, -1, -1, -1, -1,
       -1,  0, -1, -1, -1,  1,  0,  3,  1, -1,  0,  0, -1,  0, -1, -1,  0,
        0,  2, -1, -1,  3,  0,  0, -1, -1, -1, -1,  0, -1,  0,  0, -1,  0,
        0,  0, -1, -1,  0, -1, -1, -1, -1, -1,  2,  0, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1

In [48]:
cluster_label = model.labels_

In [49]:
df['cluster'] = cluster_label

In [50]:
df.head(3)

지역                               학교명  코드  유형  주야  ...  \
0  성북구  서울대학교사범대학부설중학교.....       3  국립  주간  ...   
1  종로구  서울대학교사범대학부설여자중학교...     3  국립  주간  ...   
2  강남구           개원중학교                     3  공립  주간  ...   

   location  code  type  day  cluster  
0        16     0     1    0       -1  
1        22     0     1    0       -1  
2         0     0     0    0       -1  

[3 rows x 25 columns]

In [54]:
df.columns

Index(['지역', '학교명', '코드', '유형', '주야', '남학생수', '여학생수',
       '일반고', '특성화고', '과학고', '외고_국제고', '예고_체고',
       '마이스터고', '자사고', '자공고', '기타진학', '취업', '미상', '위도',
       '경도', 'location', 'code', 'type', 'day', 'cluster'],
      dtype='object')

In [51]:
# 클러스터 값으로 그룹화하고 , 그룹별로 내용 출력 (첫 5행만 출력)

columns_list

[9, 10, 13]

In [55]:
grouped_cols = [0, 1, 3] + columns_list
grouped_cols

[0, 1, 3, 9, 10, 13]

In [57]:
grouped = df.groupby('cluster')

In [64]:
for key, group in grouped: 
    print('*key:', key)
    print('*number of group: ', len(group))
    print(group.iloc[:,grouped_cols])
    print('\n')

*key: -1
*number of group:  255
         지역                               학교명  유형  과학고  외고_국제고  \
0      성북구  서울대학교사범대학부설중학교.....    국립   0.018        0.007   
1      종로구  서울대학교사범대학부설여자중학교...  국립   0.000        0.035   
2      강남구           개원중학교                  공립   0.009        0.012   
3      강남구           개포중학교                  공립   0.013        0.013   
4      서초구           경원중학교                  공립   0.007        0.010   
..        ...                  ...                   ...     ...          ...   
376    마포구           창천중학교                  공립   0.007        0.020   
378  서대문구         가재울중학교                  공립   0.000        0.021   
379    성북구           길음중학교                  공립   0.008        0.033   
380    강서구           마곡중학교                  공립   0.000        0.024   
382    강남구           세곡중학교                  공립   0.004        0.021   

     자사고  
0     0.227  
1     0.043  
2     0.090  
3     0.065  
4     0.282  
..      ...  
376   0.101  
378   0.151  
379   0.1